security:
    password_hashers:
        App\Entity\Member:
            algorithm: auto
        App\Entity\AdminUser:
            algorithm: auto

    providers:
        member_provider:
            entity:
                class: App\Entity\Member
                property: phone

        admin_provider:
            entity:
                class: App\Entity\AdminUser
                property: login

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        admin_area:
            pattern: ^/admin
            lazy: true
            provider: admin_provider
            user_checker: App\Security\AdminUserChecker
            form_login:
                login_path: admin_login
                check_path: admin_login
                username_parameter: _login
                password_parameter: _pin
                enable_csrf: true
                default_target_path: admin_dashboard
            logout:
                path: admin_logout
                target: admin_login
            login_throttling:
                max_attempts: 5
                interval: "15 minutes"

        member_area:
            pattern: ^/espace-client
            lazy: true
            provider: member_provider
            user_checker: App\Security\MemberUserChecker
            form_login:
                login_path: member_login
                check_path: member_login
                username_parameter: _phone
                password_parameter: _pin
                enable_csrf: true
                default_target_path: member_dashboard
            logout:
                path: member_logout
                target: member_login
            login_throttling:
                max_attempts: 5
                interval: "15 minutes"

    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/espace-client/login$, roles: PUBLIC_ACCESS }
        - { path: ^/espace-client/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/espace-client, roles: ROLE_MEMBER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
