parameters:
    payslip_storage_dir: "%kernel.project_dir%/var/storage/payslips"
    contract_storage_dir: "%kernel.project_dir%/var/storage/contracts"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
